<?php $this->headTitle($this->text); ?>
<div class="row">
    <div class="col-md-4">
        <h2><?php $this->text ?></h2>
        Войти с помощью:<br>
        <ul>
            <li><a href="<?php echo $this->url('login-prepare-service', ['resourceName'=> 'GoogleOpenID']) ?>">GoogleOpenID</a></li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2><?php $this->text ?></h2>
        Зарегистрироваться с помощью:<br>
        <ul>
            <li><a href="<?php echo $this->url('login-prepare-service', ['resourceName'=> 'GoogleOpenRegisterID']) ?>">GoogleOpenID</a></li>
        </ul>
    </div>
</div>