<?php $this->headTitle("User Page"); ?>

<div class="row">
    <div class="col-md-4">
        <a href="<?php echo $this->url('logoutAR') ?>">Выйти</a>
        <div>
            <?php if (isset($this->user)) : ?>
                You name: '<?php echo $this->user['name'] ?>' <br>
                You ID: '<?php echo $this->user['id'] ?>' <br>
                <?php if (isset($this->user['roles'])) : ?>
                    You role: <br>
                    <ul>
                        <?php foreach ($this->user['roles'] as $role) : ?>
                            <li><?php echo $role ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
</div>