services:
  rollun-net-prvt:
    environment:
      OAUTH2_SERVER_PUBLIC_KEY_PATH: /data/oauth/public.key
      OAUTH2_SERVER_DB_HOST: united-db-master
      OAUTH2_SERVER_DB_NAME: oauth2_server
      OAUTH2_SERVER_DB_USER: sm://OAUTH2_SERVER_RO_DB_USER
      OAUTH2_SERVER_DB_PASS: sm://OAUTH2_SERVER_RO_DB_PASS
    volumes:
      - /ebs/containers/rollun-net-prvt/oauth-keys:/data/oauth

