<?php $this->headTitle("Logout"); ?>

<div class="row">
    <div class="col-md-4">
        <h2>
            {{ str }} <br>
            {% if user is not empty %}
            You name: '{{ user.name }}' <br>
            You ID: '{{ user.id }}' <br>
            {% if user.roles %}
            You roles:
            <ul>
                {% for role in user.roles %}
                <li>{{ role }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endif %}
        </h2>
    </div>
</div>