<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 30.01.17
 * Time: 15:55
 */

namespace rollun\permission\Api\Google\Client;

use Zend\Session\Container as SessionContainer;
use Psr\Http\Message\ServerRequestInterface as Request;


class OpenID extends ClientAbstract
{
    /** @var SessionContainer */
    protected $sessionContainer;

    public function __construct(array $config = [], SessionContainer $sessionContainer, $code = null, $clientName = null)
    {
        $this->sessionContainer = $sessionContainer;
        parent::__construct($config, $code, $clientName);
    }

    public function saveCredential($accessToken)
    {
        $this->sessionContainer->accessToken = $accessToken;
    }

    public function getSavedCredential()
    {
        return $this->sessionContainer->accessToken ?: null;
    }

    public function getCodeResponse($state)
    {
        $this->sessionContainer->state = $state;
        return parent::getCodeResponse($state); // TODO: Change the autogenerated stub
    }

    /**
     * Return user unique id.
     * An identifier for the user, unique among all Google accounts and never reused.
     * @return string|null
     */
    public function getUniqueId()
    {
        $token = $this->getAccessToken();
        $idToken = $token['id_token'];
        if ($this->verifyIdToken($idToken)) {
            $tks = explode('.', $idToken);
            list($headb64, $bodyb64, $cryptob64) = $tks;
            $playload = json_decode(base64_decode($bodyb64));
            return $playload->sub;
        }
        return null;
    }

    public function initCode(Request $request)
    {
        $query = $request->getQueryParams();
        if (isset($query['code'])) {
            $this->setCode($query['code']);
        }
    }
}
